### ISSUE TITLE
Transmit Output error High SWR Big Red Box on Panadapter Screen [BUG]

### ISSUE THREAD

**Issue by Larry-W8ER** [sjk7/Thetis-2.9.0#22]
**Describe the bug**
Version 2.9.0.19 I get HIGH SWR warning with a big red warning box displayed on the panadapter in transmit or tune. I have multi-meter set to display forward power and SWR. When I click "tune" the meter needles peg to the right and then quickly decay. Bird dummy load with Meter Builders MB-1 and PowerMaster wattmeters show no such pulse on the output. Actually no RF period. Tried second dummy load, no different

Switched radio to Anan 10e and no problem, works perfectly. Version 2.9.0.19 same under Win10 and Win11. Running i9 on Asus motherboard, 32G RAM 500G SSD. Did fresh installs of each OS with Fresh Thetis 2.9.0.19 installs. Saw the same problem with .18 version.

Hermes Lite 2 from latest build works fine with 2.9.0.8 using Ritchie build and mi0bot mods. 

**To Reproduce**
Simple and repeatable, not intermittent. Basic load of OS and updates to present and fresh install of Thetis (.18 and .19). Using Hermes Lite 2 from recent build. 

**Expected behaviour**
Uh .. after loading, using default settings except selecting Hermes, N2ADR, PA settings (default) VAC1.. typical others .. I would expect output on "tune" not error. Went back and tried Hermes after using Anan successfully. Same problem again with Hermes. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows10 and Windows11 both fresh install and updated to present.

**Additional context**
No, except to note that the HL2 works well with 2.9.0.8 Ritchie and mi0bot versions and that Anan 10e works well with G7KLJ versions 2.9.0.18 and .19. Thanks Steve -- Larry W8ER

**Comment by sjk7** [comment]
Hello,
First things first. Is the power showing the correct power when this happens? It bases all its calculations on that, so, if it is out of bonk, you will see this.

Also please check whether or not the SWR protection settings are different. They are buried in the setup window.

I use a HL2, and the swr protection seems to work well for me. But then I always tick HL2 and N2ADR when using it. It sets up a lot of stuff for you. I think these pictures might be useful, thou. Let me know if I have the wrong end of the stick here. It happens! ;-)

![CalibPower](https://user-images.githubusercontent.com/24289173/233605698-e0f6b109-ca88-4efb-913a-0baa7e491433.jpg)
![swr](https://user-images.githubusercontent.com/24289173/233605712-ef29af93-499d-4500-af6a-46931c12a5ae.jpg)

**Comment by Larry-W8ER** [comment]
Hi Steve,

Thanks for the instant reply and the work on Thetis for the HL2! I've been running .19 with my Anan  -- 10E -- for 2 mornings now and it's better than fine. This must be Christmas and you must be Santa!

**The transceiver which runs perfectly is the Anan  --10E-- 15 watts out max.**

Your Q. "First things first. Is the power showing the correct power when this happens? It bases all its calculations on that, so, if it is out of bonk, you will see this.

Ans. Have not changed either PA gain settings or Wattmeter setting from default.

Your Q. "Also please check whether or not the SWR protection settings are different. They are buried in the setup window."

Ans. Exactly same.

Your Q. "I use a HL2, and the swr protection seems to work well for me. But then I always tick HL2 and N2ADR when using it. It sets up a lot of stuff for you. I think these pictures might be useful, thou. Let me know if I have the wrong end of the stick here. It happens! ;-)

Ans. Questions here. On setup screen I check Hermes .. note that Alex is checked by default.

![Picture0001](https://user-images.githubusercontent.com/104642724/233662365-1097d4f6-c1ea-489f-ba02-a5fda88bebf7.jpg)

Next, under Hardware Options, I check Hermes Lite 2 and filter changes from Alex to Apollo. When this happens, and the Alex tab is selected, the whole screen is greyed out. (seems right)

![Picture0002](https://user-images.githubusercontent.com/104642724/233663238-fa3bcf8d-ace4-47c8-bbf7-9ab90b75ff30.jpg)

When I go back to Hardware Options and select Alex, instead of Apollo, here is my Alex tab, same as your.

![Picture0003](https://user-images.githubusercontent.com/104642724/233663795-53b0e5cd-09ed-4d87-abd8-8ef621934067.jpg)

PA Gain settings all at 38.8 (default) not changed  Did not calibrate the Wattmeter setting (default)

Next I go to Main Display and click "TUNE" and red warning of HIGH SWR appears. Note meter is set on FWD POWER. Meter needle has already pegged and is dropping when screenshot taken. No actual power showing on external wattmeter which samples 500/sec and holds display. (no RF out to dummy)

![Picture0006](https://user-images.githubusercontent.com/104642724/233665343-9b642f75-4a4d-4f21-aa44-b57c10c0234e.jpg)

Also note that on this screenshot, the meter is showing SWR (6.4:1) but falls back to 1:1.

![Picture0007](https://user-images.githubusercontent.com/104642724/233665853-f1d8a0cd-a657-44dd-a23a-9ac2d1961e0c.jpg)

I have checked my dummy load. Tried different cables. Tried different wattmeter. The results all the same.

Moved from Hermes to Anan 10E  --  NO PROBLEM.

Loaded Ritchie's 2.9.0.8 and mi0bot's modded files and Hermes works perfectly.

I tried fresh load of both Win10 and Win11, updated to present. I get the exact same results on both OS's. This was version .18 but I reset and did same tests on .19, which I am now running and the results are exactly the same. **I am at your service SIR!**

**Comment by sjk7** [comment]
Ok, we'll look into this more. Am I correct that it only fails with HL2 for you? Anan is ok?
Steve

**Comment by Larry-W8ER** [comment]
Steve ... I have already tried it with a fresh database (install default), making only the changes necessary to see the radio and radio type (several times>6). **Never** imported saved database into any install.

**Your HL2 from this last batch #10?** I believe that different firmware is loaded in HL2 from previous batches.

Only fails with HL2 .. **Anan 10E perfect.**

Disable SWR Protection ???  Will try it after taking blood pressure medication.

I am setting up a new Win11 system for test. Will download fresh 2.9.0.19 

Thank you Steve.

--Larry

**Comment by sjk7** [comment]
Heh. You made me chuckle. Just testing here, but I cannot get it to trip even with like 2:1 swr, at least on 160m. Ramdor releases are from Richie, and it is that that is the base for this build. No, it doesn't load firmware nor does it run a different protocol than before.

Having said that, I did manually update the firmware on my HL2 about 2 weeks ago, but totally unrelated to this version of Thetis.

Steve

**Comment by Larry-W8ER** [comment]
Steve ... Just brought up 2.9.0.19 under fresh Win11. Same. 

Unchecked "enable protection" Drive control set at 50. Power out on external meters .98 watts, no error. 

Increased Drive to 55. Output jumped instantly to 4.28 watts and ADC 1 Overload at bottom of panadapter popped up.

OK ... need link to instructions to upgrade firmware and link to firmware that you are using.  

-- Larry

**Comment by Larry-W8ER** [comment]
Steve 

Batch #10 from Makerfabs (not Ramdor 😏) is doing something different because of chip shortage. It is my impression that the firmware has changed from Batch #9. I am not sure however. I will do some research on that.

You may not want me to change it yet, so I will wait for your instructions, no matter what. The firmware in my HL2 is what it was shipped with which is 7.3 ID 6 Protocol 1.

--Larry

**Comment by Archcantor** [comment]
I have one of those MFJ SDR relays on my ANAN 7000 antenna line. It allows my SDRPlay to tap into the Anan's antenna and protect the SDRPlay. Around the same time I loaded the 2.9.0.18 I accidentally unplugged the PTT line from the MFJ relay.  It still worked because the MFJ as RF sense but there was around a 100 ms detection time. The Anan 7000 was briefly flashing HIGH SWR and tripping on MOX start. When I reconnected the PTT line, the MFJ now switched before the Anan RF started and all was well again.  So try connecting a dummy load directly and see if the SWR trips again.  By the way, the SWR protection did not trip on MOX start with Ramdor's 2.9.0.8 even though the HIGH SWR briefly flashed.  This tripping sounds like the radio is transmitting during an antenna relay change.  Maybe increase the RF Delay on the Options-1 Tab.  It can be set to as high as 500 ms.  Just some thoughts since my problem was ME and not Thetis.  Rick, W1RHS

**Comment by sjk7** [comment]
@Larry-W8ER Does the above help? Are you plugging in the dummy _direct_?

**Comment by Larry-W8ER** [comment]
Steve, I was not plugging directly into the dummy initially. After reading the above, although skeptical that it had any relevance to my configuration, I tried it. Essentially, I come out of the HL2 to the input my SS amp, which has never been turned on for any of these tests, into a sensor for the MB-1 and then to the dummy. It's a minimal configuration.

I have a small 100 watt dummy that I connected to my MB-1 sensor and then to the HL2 for the most recent tests. I see no difference in the way the HL2 acts.

**I am puzzled about the way it behaves when the Protection is turned off. Using the "tune" button and the drive set to 50, I see .98 watts of output. No errors, no problems. Increasing the drive control to a setting of 55, the wattmeter shows 4.9 watts and the "ADC 1 Overload" indicator active at the bottom of the panadapter.**

Is there a link to an earlier version of your implementation of Thetis, say 2.9.0.10 or 2.9.0.11? I have looked for it an cannot find it anywhere. I would be very interested in trying it, as it is much closer to the fork.  Thanks -- Larry

**Comment by PaulGB1** [comment]
SWR Issue here too

**Comment by Larry-W8ER** [comment]
Steve,

I greatly appreciate your work on Thetis as I am sure others do too. The fixes in the VAC area are super! Overall excellent work!

Your "changelog" indicates something happening on 4-2-2023 **"Sun Apr 2 13:49:57 2023 +0100 - sjk7: New High SWR notification method (needs testing) Make averaging enabled or not more consistent between console and setup"** 

???

I've loaded Dot 18 and 19 on fresh loads of Win11, Win10 and on an Intel NUC 10i7 and a homebrew i9 and it's failed the same way everytime regardless of platform. Ritchie's Dot 8 with mi0bot's Dot 8 mods do not show any failures on the Hermes Lite 2 or the Anan 10E.

I found your version Dot 15 and it fails the same way as the later versions, 18 and 19.

Please ... I can only provide further help now with a DotX version installer that is closer to the "fork", preferably prior to the reference in your changelog entry of April 2. 

Thanks for your work --- Larry W8ER

**Comment by nj2us** [comment]
> Ok, we'll look into this more. Am I correct that it only fails with HL2 for you? **Anan is ok?**
> Steve

Anan 7000DLE data point, Win 11,  Release 2.9.0.19, working fine, SWR functionality is OK.

NJ2US

**Comment by Larry-W8ER** [comment]
Dot 19 checked with Anan 10E, 7000DLE and 200D --- PERFECT NO PROBLEM!

PROBLEM OBVIOUS AND SOLID WITH Hermes Lite 2 ...   and Dots 15, 18 19 on i7 and i9 computers with fresh loads of Win10 and Win11 .... starting with new databases each time.

I would be willing to test builds after original fork from Ritchie's code, up to Apr 2 entry into Changelog ...
**""" Sun Apr 2 13:49:57 2023 +0100 - sjk7: New High SWR notification method (needs testing) Make averaging enabled or not more consistent between console and setup """**

**Comment by sjk7** [comment]
There are some data races between who in the program sets the forward power and reflected power, as well as the S-Meter. This is why it sometimes pegs as you go into RX. It is PROPER flaky, depending on whether you have hyper-threading enabled on old machines, and just how many cores you have on a modern machine.

The more cores you have, the more likely it is to FU.

I did some work on it Friday, and so you might see an improvement in the next release in the next day or 2.

Steve

**Comment by sjk7** [comment]
Thanks for kind words. I will try to update the msi installer in the morning,
Steve

**Comment by sjk7** [comment]
Nothing for you today, unfort I have used all my spare time (and more) finding a finicky and awkward bug in channelmaster. Let's hope for better things tomorrow, though I do have a busy week ahead.

Steve

**Comment by sjk7** [comment]
Closed as this should be addressed in next revision. You can still feedback to closed tickets, and, if need be, they can be reopened,
Steve

**Comment by Archcantor** [comment]
Steve, your work is very much appreciated.  -Rick, W1RHS

**Comment by PaulGB1** [comment]
Steve - your work is very much appreciated.

HL2 with GW7.3p2, Win11, Thetis V2.9.0.24 - I am sorry but still have SWR flashing this side. Would you kindly provide images of your setup screens as you have it working with HL2....im sure its a wrong setting or something here! TIA Paul

**Comment by Larry-W8ER** [comment]
Steve, I echo the thought of Paul and Rick and I am sure many others.

I have tried 20 23 and now 26 and have been reluctant to post my results. The SWR problem still exists here. Now it is joined by several others, such as when using the additional meters, I have indications of 58 watts of RF on receive from the Forward Power Meter and -0- meter deflection of mic audio on transmit.  In 20 and 23 I had no transmit audio thru VAC1 and in 26, I have audio but still no meter indication of it being present. 

I have noticed that on the SetUP/General/PA Settings/Wattmeter tab, I am seeing the 100 watt calibration settings not those of version 19 for the lower power Hermes. That is on the Hermes.

On the Anan, I gave up when I could get no transmit audio to the Anan and yes I have unchecked the box "Allow PTT to override/bypass VAC for Phone".

As always, I load a fresh version of Windows and then install a fresh download of your Thetis. I do not import any database but configure each version from the start. The only issue I had with version 19 and the Hermes was the SWR problem. On versions 20 23 and 26 the issue was still the same except that it happened at a different drive setting. At settings greater than 70, the problem of SWR protect would occur and it did not care where the PA Gain settings were set.

If it would help you, I would be more than willing to take a screen shot of every setup screen where I have made ANY change to the default.  I recognize what a tedious project this is for you and I wish I could do more to help.

--Larry W8ER

**Comment by nj2us** [comment]
Data Point from Nj2US

Windows 11 Pro
Thetis v2.9.0.26
FW 2.1.18
Anan 7000dle dedicated ETH interface

No issues, No SWR Problems, No Antenna Switching issues, VAC and PS working GREAT, concluding that .26 is a stable release, AT LEAST FOR ME, Your Mileage probably varies.
NOTE: I UNCHECK ALL SWR Protection in Thetis on the Ant/Tabs, as the Anan firmware properly folds back TX power with bad matches.

-NJ2US

**Comment by Larry-W8ER** [comment]
Hi Jeff ... My hardware is an Anan 10e and a Hermes Lite 2. I am not sure that my firmware would foldback power on an improper load. While I have disabled SWR protection for testing, I would not do so for normal operation nor would I wire around fuses or breakers or climb into a pilots seat without a walk-a-round! Pre-flight testing here on both the Anan and the Hermes tells me something different, sorry!  -- Larry W8ER

**Comment by nj2us** [comment]
Multi meters are fine in .26

I just ran a shift of ECARS on 7255 kHz running .26, never skipped a beat. 

I'd be shocked if the Hermes L2 couldn't properly handle a bad load. 

Clearly your mileage varies!

73,

NJ2US

**Comment by PaulGB1** [comment]
Hi Jeff,

I'm delighted it works for you on the Anan but I believe it is HL2 related issue. I have asked if Steve would kindly provide screenshots of the setup pages on his own installation which works with the HL2 (Also which gateware if not latest stable one). FYI Unchecking SWR protection stopped the high SWR main screen but the meters still report high SWR and crazy power output, this does not happen with the version from Reid Mi0BOT. I do not have an high SWR on a 50ohm dummy load :)

Really keen to use this version from Steve and really hoping we can get past the SWR issue with the HL2.

Waiting patiently for the next version .TIA 73 Paul 2e0ymt

**Comment by sjk7** [comment]
Hello Paul,
I am adding a couple screenies of my setup. You'll note there is no fantastic way to set the power for an HL2, currently. I just adjust the controls so the power shows about x10 of the actual output: so 45W means 4.5W. This makes the swr trip too early, but its good enough for my usage. Couple screenshots 4 u, @PaulGB1 :
![HL2Setup](https://user-images.githubusercontent.com/24289173/235324557-be7778fb-25cc-4c18-b2b0-1ca35e900a16.jpg)
![HL2SWR](https://user-images.githubusercontent.com/24289173/235324558-5e3041e0-4054-4e7c-8a12-ccbc2e571431.jpg)

**Comment by Larry-W8ER** [comment]
Steve ... I loaded .27 this morning. Anan 10e works perfect. No SWR protect problem. No audio problem. No meter problem Fine Super. I reset DB and changed to Hermes. Works. I had to disable SWR protect. No audio problem. No meter problem. VAC perfect.

Only wish here ... Hermes power out indicator fix (indicator not control) --- SWR Protect issue. (Maybe same root cause??)

Nice work Steve!  -- Larry W8ER

**Comment by sjk7** [comment]
Yeh, I set my power readings to be x10 what they really are.

This makes SWR protection kick in early, but what the hey!

**Comment by PaulGB1** [comment]
Hi Steve,

This evening I loaded .29 did a full dtb reset. Same screen high SWR border on panadapter and the meters read crazy numbers both SWR & PWR. Turn off protection the main screen is fine but teh meters scare the life outta me!!

Something is A LOT more sensitive now in these builds as ive never experienced this before.

I have 2 HL2's will try the other tomorrow and also move the 50ohm load from the amp ANT2 and put it direct to the radio.  Will report back in a couple of days.

Keep up the brilliant work, Steve...don't burn out mate.

73 Paul
